### ISSUE TITLE
CountryName

### ISSUE THREAD

**Issue by IanaKhitsko** [WNikolassss/euro-diffusion#1]
https://github.com/WNikolassss/euro-diffusion/blob/f2ed5ab59696eea11903bd433b01bebbafa672bf/models/city.model.ts#L6

You use country name only for getting index. Can you use only index or do not save it at all ?

**Comment by WNikolassss** [comment]
The country name is also used for logging to the end-user.
The index will be stored anyway so we can address it when calculating coins.
