### ISSUE TITLE
Use one operator?

### ISSUE THREAD

**Issue by IanaKhitsko** [WNikolassss/euro-diffusion#2]
https://github.com/WNikolassss/euro-diffusion/blob/f2ed5ab59696eea11903bd433b01bebbafa672bf/models/country.model.ts#L49-L52

return  (Number.isInteger(coordinate)) &&
        coordinate >= Country.MIN_COORDINATE &&
        coordinate <= Country.MAX_COORDINATE
      );

?

**Comment by WNikolassss** [comment]
Agree, will be merged into the upcoming update.

**Comment by WNikolassss** [comment]
Fixed by https://github.com/WNikolassss/euro-diffusion/commit/e2590fea5d6e228e148cb14dc4fa98d9315c9f93
