### ISSUE TITLE
Variable definition in condition

### ISSUE THREAD

**Issue by IanaKhitsko** [WNikolassss/euro-diffusion#3]
https://github.com/WNikolassss/euro-diffusion/blob/f2ed5ab59696eea11903bd433b01bebbafa672bf/models/map.model.ts#L98-L99

Do you have the ability to define variables inside the condition in typestript? Like
          if (const neighborCity = this.countriesGrid.get({ x, y })) { ...    
?

**Comment by WNikolassss** [comment]
Not available in TypeScript
