### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by kirick1** [WNikolassss/euro-diffusion#5]
https://github.com/WNikolassss/euro-diffusion/blob/e2590fea5d6e228e148cb14dc4fa98d9315c9f93/models/country.model.ts#L26
Why not to use validation on setter for property?

**Comment by WNikolassss** [comment]
This validation is placed in the constructor so if an error will occur it won't go further for calculations for other fields, validations etc and no need to create an additional property for setter because we don't reassign this var anywhere.
