### ISSUE TITLE
Safe reading file

### ISSUE THREAD

**Issue by kirick1** [WNikolassss/euro-diffusion#6]
https://github.com/WNikolassss/euro-diffusion/blob/e2590fea5d6e228e148cb14dc4fa98d9315c9f93/file.input.ts#L10
Better to define encoding for file, for example utf-8 that to safely use splitting by \n symbol. Or you can use readline module from NodeJs core

**Comment by WNikolassss** [comment]
Agree. Fixed in https://github.com/WNikolassss/euro-diffusion/commit/047f883f4fac0d978ec0a00f89799bcf90f556d0
