### ISSUE TITLE
Replace initialization to separated method

### ISSUE THREAD

**Issue by kirick1** [WNikolassss/euro-diffusion#7]
https://github.com/WNikolassss/euro-diffusion/blob/e2590fea5d6e228e148cb14dc4fa98d9315c9f93/models/map.model.ts#L38
I think will be better to replace initialization of coordinates to separate method of MapGrid class that will return void

**Comment by WNikolassss** [comment]
Agree. Will just be moved to the default value for this props. Fixed in https://github.com/WNikolassss/euro-diffusion/commit/047f883f4fac0d978ec0a00f89799bcf90f556d0
