### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kirick1** [WNikolassss/euro-diffusion#8]
https://github.com/WNikolassss/euro-diffusion/blob/e2590fea5d6e228e148cb14dc4fa98d9315c9f93/models/map.model.ts#L80
This should not work because JavaScript will create new unique reference to object every time when you set value by this way, so you will not be able to get value. Better will be to transform this coordinate pair to string.

**Comment by WNikolassss** [comment]
Not relevant because the key for GridDictionary is constructed from '${x}-${y}' string.
Check here: https://github.com/WNikolassss/euro-diffusion/blob/e2590fea5d6e228e148cb14dc4fa98d9315c9f93/models/map.model.ts#L9
